services:
  api-01:
    image: nmatsui/hello-world-api
    ports:
      - "3000:3000"
    environment:
      MESSAGE: ${MESSAGE}

  api-02:
    image: nmatsui/hello-world-api
    ports:
      - "3001:3000"
    environment:
      MESSAGE: ${MESSAGE}

  api-03:
    image: nmatsui/hello-world-api
    ports:
      - "3002:3000"
    environment:
      MESSAGE: ${MESSAGE}

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: lab02-bandaorbegoso
    volumes:
      - lab02_pgdata:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  lab02_pgdata:
